version: '3'
services:
  admin-app:
    container_name: "admin-app"
    build: 
      context: app/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-net
    depends_on:
      - admin-mariadb
    volumes:                  
      - ./app:/app 

  admin-mariadb:
    container_name: "admin-mariadb"
    build: 
      context: db/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: local-python2023
      MYSQL_PASSWORD: password
    networks:
      - app-net
    volumes:
      - .db:/var/lib/mysql

networks:
  app-net:
    driver: bridge

    